sqlldr userid="GW_ABC123_USER/asdqwe123$%^" control=D:\[개발하자]\[우편번호]\일괄등록_2015.08\ZIP_ORACLE\ctrl\EM_ADR_BLD_INFO_B_ALL_01.ctrl log=D:\[개발하자]\[우편번호]\일괄등록_2015.08\ZIP_ORACLE\control.log
sqlldr userid="GW_ABC123_USER/asdqwe123$%^" control=D:\[개발하자]\[우편번호]\일괄등록_2015.08\ZIP_ORACLE\ctrl\EM_ADR_BLD_INFO_B_ALL_02.ctrl log=D:\[개발하자]\[우편번호]\일괄등록_2015.08\ZIP_ORACLE\control.log
sqlldr userid="GW_ABC123_USER/asdqwe123$%^" control=D:\[개발하자]\[우편번호]\일괄등록_2015.08\ZIP_ORACLE\ctrl\EM_ADR_BLD_INFO_B_ALL_03.ctrl log=D:\[개발하자]\[우편번호]\일괄등록_2015.08\ZIP_ORACLE\control.log
sqlldr userid="GW_ABC123_USER/asdqwe123$%^" control=D:\[개발하자]\[우편번호]\일괄등록_2015.08\ZIP_ORACLE\ctrl\EM_ADR_BLD_INFO_B_ALL_04.ctrl log=D:\[개발하자]\[우편번호]\일괄등록_2015.08\ZIP_ORACLE\control.log
sqlldr userid="GW_ABC123_USER/asdqwe123$%^" control=D:\[개발하자]\[우편번호]\일괄등록_2015.08\ZIP_ORACLE\ctrl\EM_ADR_BLD_INFO_B_ALL_05.ctrl log=D:\[개발하자]\[우편번호]\일괄등록_2015.08\ZIP_ORACLE\control.log
sqlldr userid="GW_ABC123_USER/asdqwe123$%^" control=D:\[개발하자]\[우편번호]\일괄등록_2015.08\ZIP_ORACLE\ctrl\EM_ADR_BLD_INFO_B_ALL_06.ctrl log=D:\[개발하자]\[우편번호]\일괄등록_2015.08\ZIP_ORACLE\control.log
sqlldr userid="GW_ABC123_USER/asdqwe123$%^" control=D:\[개발하자]\[우편번호]\일괄등록_2015.08\ZIP_ORACLE\ctrl\EM_ADR_BLD_INFO_B_ALL_07.ctrl log=D:\[개발하자]\[우편번호]\일괄등록_2015.08\ZIP_ORACLE\control.log
sqlldr userid="GW_ABC123_USER/asdqwe123$%^" control=D:\[개발하자]\[우편번호]\일괄등록_2015.08\ZIP_ORACLE\ctrl\EM_ADR_BLD_INFO_B_ALL_08.ctrl log=D:\[개발하자]\[우편번호]\일괄등록_2015.08\ZIP_ORACLE\control.log
sqlldr userid="GW_ABC123_USER/asdqwe123$%^" control=D:\[개발하자]\[우편번호]\일괄등록_2015.08\ZIP_ORACLE\ctrl\EM_ADR_BLD_INFO_B_ALL_09.ctrl log=D:\[개발하자]\[우편번호]\일괄등록_2015.08\ZIP_ORACLE\control.log
sqlldr userid="GW_ABC123_USER/asdqwe123$%^" control=D:\[개발하자]\[우편번호]\일괄등록_2015.08\ZIP_ORACLE\ctrl\EM_ADR_BLD_INFO_B_ALL_10.ctrl log=D:\[개발하자]\[우편번호]\일괄등록_2015.08\ZIP_ORACLE\control.log
sqlldr userid="GW_ABC123_USER/asdqwe123$%^" control=D:\[개발하자]\[우편번호]\일괄등록_2015.08\ZIP_ORACLE\ctrl\EM_ADR_BLD_INFO_B_ALL_11.ctrl log=D:\[개발하자]\[우편번호]\일괄등록_2015.08\ZIP_ORACLE\control.log
sqlldr userid="GW_ABC123_USER/asdqwe123$%^" control=D:\[개발하자]\[우편번호]\일괄등록_2015.08\ZIP_ORACLE\ctrl\EM_ADR_BLD_INFO_B_ALL_12.ctrl log=D:\[개발하자]\[우편번호]\일괄등록_2015.08\ZIP_ORACLE\control.log
sqlldr userid="GW_ABC123_USER/asdqwe123$%^" control=D:\[개발하자]\[우편번호]\일괄등록_2015.08\ZIP_ORACLE\ctrl\EM_ADR_BLD_INFO_B_ALL_13.ctrl log=D:\[개발하자]\[우편번호]\일괄등록_2015.08\ZIP_ORACLE\control.log
sqlldr userid="GW_ABC123_USER/asdqwe123$%^" control=D:\[개발하자]\[우편번호]\일괄등록_2015.08\ZIP_ORACLE\ctrl\EM_ADR_BLD_INFO_B_ALL_14.ctrl log=D:\[개발하자]\[우편번호]\일괄등록_2015.08\ZIP_ORACLE\control.log
sqlldr userid="GW_ABC123_USER/asdqwe123$%^" control=D:\[개발하자]\[우편번호]\일괄등록_2015.08\ZIP_ORACLE\ctrl\EM_ADR_BLD_INFO_B_ALL_15.ctrl log=D:\[개발하자]\[우편번호]\일괄등록_2015.08\ZIP_ORACLE\control.log
sqlldr userid="GW_ABC123_USER/asdqwe123$%^" control=D:\[개발하자]\[우편번호]\일괄등록_2015.08\ZIP_ORACLE\ctrl\EM_ADR_BLD_INFO_B_ALL_16.ctrl log=D:\[개발하자]\[우편번호]\일괄등록_2015.08\ZIP_ORACLE\control.log
sqlldr userid="GW_ABC123_USER/asdqwe123$%^" control=D:\[개발하자]\[우편번호]\일괄등록_2015.08\ZIP_ORACLE\ctrl\EM_ADR_BLD_INFO_B_ALL_17.ctrl log=D:\[개발하자]\[우편번호]\일괄등록_2015.08\ZIP_ORACLE\control.log

