sqlldr userid="GW_LINUX_USER/asdqwe123$%^@DEVDB" control=/oradata/zipData/ctrl/EM_ADR_BLD_INFO_B_ALL_01.ctrl log=/oradata/zipData/control.log
sqlldr userid="GW_LINUX_USER/asdqwe123$%^@DEVDB" control=/oradata/zipData/ctrl/EM_ADR_BLD_INFO_B_ALL_02.ctrl log=/oradata/zipData/control.log
sqlldr userid="GW_LINUX_USER/asdqwe123$%^@DEVDB" control=/oradata/zipData/ctrl/EM_ADR_BLD_INFO_B_ALL_03.ctrl log=/oradata/zipData/control.log
sqlldr userid="GW_LINUX_USER/asdqwe123$%^@DEVDB" control=/oradata/zipData/ctrl/EM_ADR_BLD_INFO_B_ALL_04.ctrl log=/oradata/zipData/control.log
sqlldr userid="GW_LINUX_USER/asdqwe123$%^@DEVDB" control=/oradata/zipData/ctrl/EM_ADR_BLD_INFO_B_ALL_05.ctrl log=/oradata/zipData/control.log
sqlldr userid="GW_LINUX_USER/asdqwe123$%^@DEVDB" control=/oradata/zipData/ctrl/EM_ADR_BLD_INFO_B_ALL_06.ctrl log=/oradata/zipData/control.log
sqlldr userid="GW_LINUX_USER/asdqwe123$%^@DEVDB" control=/oradata/zipData/ctrl/EM_ADR_BLD_INFO_B_ALL_07.ctrl log=/oradata/zipData/control.log
sqlldr userid="GW_LINUX_USER/asdqwe123$%^@DEVDB" control=/oradata/zipData/ctrl/EM_ADR_BLD_INFO_B_ALL_08.ctrl log=/oradata/zipData/control.log
sqlldr userid="GW_LINUX_USER/asdqwe123$%^@DEVDB" control=/oradata/zipData/ctrl/EM_ADR_BLD_INFO_B_ALL_09.ctrl log=/oradata/zipData/control.log
sqlldr userid="GW_LINUX_USER/asdqwe123$%^@DEVDB" control=/oradata/zipData/ctrl/EM_ADR_BLD_INFO_B_ALL_10.ctrl log=/oradata/zipData/control.log
sqlldr userid="GW_LINUX_USER/asdqwe123$%^@DEVDB" control=/oradata/zipData/ctrl/EM_ADR_BLD_INFO_B_ALL_11.ctrl log=/oradata/zipData/control.log
sqlldr userid="GW_LINUX_USER/asdqwe123$%^@DEVDB" control=/oradata/zipData/ctrl/EM_ADR_BLD_INFO_B_ALL_12.ctrl log=/oradata/zipData/control.log
sqlldr userid="GW_LINUX_USER/asdqwe123$%^@DEVDB" control=/oradata/zipData/ctrl/EM_ADR_BLD_INFO_B_ALL_13.ctrl log=/oradata/zipData/control.log
sqlldr userid="GW_LINUX_USER/asdqwe123$%^@DEVDB" control=/oradata/zipData/ctrl/EM_ADR_BLD_INFO_B_ALL_14.ctrl log=/oradata/zipData/control.log
sqlldr userid="GW_LINUX_USER/asdqwe123$%^@DEVDB" control=/oradata/zipData/ctrl/EM_ADR_BLD_INFO_B_ALL_15.ctrl log=/oradata/zipData/control.log
sqlldr userid="GW_LINUX_USER/asdqwe123$%^@DEVDB" control=/oradata/zipData/ctrl/EM_ADR_BLD_INFO_B_ALL_16.ctrl log=/oradata/zipData/control.log
sqlldr userid="GW_LINUX_USER/asdqwe123$%^@DEVDB" control=/oradata/zipData/ctrl/EM_ADR_BLD_INFO_B_ALL_17.ctrl log=/oradata/zipData/control.log

